"""empty message

Revision ID: 01e15076066f
Revises: None
Create Date: 2017-08-18 20:15:40.300280

"""

# revision identifiers, used by Alembic.
revision = '01e15076066f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposition_name'), 'proposition', ['name'], unique=True)
    op.create_table('senator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('party', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=5), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('twitter', sa.String(length=120), nullable=True),
    sa.Column('facebook', sa.String(length=120), nullable=True),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook'),
    sa.UniqueConstraint('instagram'),
    sa.UniqueConstraint('twitter')
    )
    op.create_index(op.f('ix_senator_name'), 'senator', ['name'], unique=True)
    op.create_index(op.f('ix_senator_party'), 'senator', ['party'], unique=False)
    op.create_index(op.f('ix_senator_state'), 'senator', ['state'], unique=False)
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Enum('positive', 'negative', 'absence', 'abstention', name='votetype'), nullable=True),
    sa.Column('senator', sa.Integer(), nullable=True),
    sa.Column('proposition', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposition'], ['proposition.id'], ),
    sa.ForeignKeyConstraint(['senator'], ['senator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_index(op.f('ix_senator_state'), table_name='senator')
    op.drop_index(op.f('ix_senator_party'), table_name='senator')
    op.drop_index(op.f('ix_senator_name'), table_name='senator')
    op.drop_table('senator')
    op.drop_index(op.f('ix_proposition_name'), table_name='proposition')
    op.drop_table('proposition')
    # ### end Alembic commands ###
